### PR TITLE
Multiple bugfixes

### PR DESCRIPTION
**Pull request by Genbox**
See each commit for the content of this pull request. There are a couple of bugfixes and a few small performance improvements. I tried to keep the changes in each commit minimal so they are easier to review.

### CODE REVIEW

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — COMMENTED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — COMMENTED** [review]
There is a problem here but it has to be fixed in another way. I'm going to merge this and then fix it permanently

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — COMMENTED** [review]
This would be correct but only in the windows world. not all dlls have the name in lowercase, formally it is more correct to put all lowercase or uppercase

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Review by b4rtik — APPROVED** [review]

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Comment by Genbox** [comment]
Thanks for taking the time to look at this. Let me know if you have any questions.

**Review by b4rtik — APPROVED** [review]
This is correct and can be merged

**Comment by b4rtik** [comment]
I would like to thank you for doing this careful review of the code. Thank you!

**Comment by b4rtik** [comment]
A future try to take this into consideration: When you create an offensive tool you should always keep in mind that the code should be as generic as possible so that it can be compiled with different versions of the framework. For example it seems that Array.Empty is only available from 4.6 onwards. This does not allow me to use the tool on machines with framwork less than 4.6 ... and there are many;)

**Comment by Genbox** [comment]
Arh, sorry about that. I had to upgrade from .NET 4.0 to 4.6 as the SDK for .NET 4.0 was not among the ones listed on the [official download page](https://dotnet.microsoft.com/download/visual-studio-sdks). I misremembered that Array.Empty<T> was part of .NET 4.0 too.

 I usually only target .NET Standard 2.0 for all my projects which works cross-platform with the .NET Core runtime.

**Pull request merged**
